# Generated by Django 3.0.5 on 2020-04-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt', models.CharField(max_length=100)),
                ('acayear', models.IntegerField()),
                ('expdate', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
    ]
