# Generated by Django 3.0.5 on 2020-04-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dpt', models.CharField(max_length=100)),
                ('acayear', models.IntegerField(default=1)),
                ('funq', models.CharField(max_length=200)),
            ],
        ),
    ]
