# Generated by Django 3.0.5 on 2020-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_regimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uindex', models.CharField(max_length=30)),
                ('imgname', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='RegImage',
        ),
    ]
